name: Deploy to Google Cloud Platform

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual trigger

env:
  NODE_VERSION: '20'
  GCP_PROJECT_ID: 'throp-469410'
  GCP_REGION: 'us-central1'
  GCP_SERVICE_NAME: 'throp-bot'

jobs:
  # 1. Run tests and build
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps
      
      - name: Run linter
        run: npm run lint
        continue-on-error: true  # Don't fail on lint warnings
      
      - name: Build project
        run: npm run build
      
      - name: Build frontend
        run: |
          cd web
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          npm run build
        continue-on-error: true  # Frontend build is separate

  # 2. Deploy Backend to GCP Cloud Run
  deploy-backend:
    name: Deploy Backend to GCP
    needs: [test-and-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      
      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.GCP_SERVICE_NAME }} \
            --source . \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --quiet
      
      - name: Get Service URL
        id: get-url
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.GCP_SERVICE_NAME }} \
            --region ${{ env.GCP_REGION }} \
            --format 'value(status.url)')
          echo "service_url=$SERVICE_URL" >> $GITHUB_OUTPUT
          echo "Backend deployed to: $SERVICE_URL"
      
      - name: Health Check
        run: |
          sleep 30  # Wait for deployment to stabilize
          
          SERVICE_URL="${{ steps.get-url.outputs.service_url }}"
          echo "Testing health endpoint: $SERVICE_URL/health"
          
          # Retry health check up to 5 times
          for i in {1..5}; do
            if curl -sf "$SERVICE_URL/health" > /dev/null; then
              echo "✅ Backend health check passed on attempt $i!"
              break
            else
              echo "⚠️ Health check failed on attempt $i, retrying..."
              sleep 10
            fi
            
            if [ $i -eq 5 ]; then
              echo "❌ Health check failed after 5 attempts"
              exit 1
            fi
          done
          
          # Test additional endpoints
          echo "Testing status endpoint..."
          curl -sf "$SERVICE_URL/api/status" || echo "⚠️ Status endpoint not ready"
          
          echo "Testing Twitter diagnostics..."
          curl -sf "$SERVICE_URL/api/twitter/diagnostics" || echo "⚠️ Twitter diagnostics not ready"

  # 3. Deploy Frontend to Netlify
  deploy-frontend:
    name: Deploy Frontend to Netlify
    needs: [test-and-build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      
      - name: Install dependencies and build
        run: |
          cd web
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          npm run build
      
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd web
          netlify deploy --prod --dir=.next
      
      - name: Frontend Health Check
        run: |
          sleep 20
          
          FRONTEND_URL="https://throp.ai"
          echo "Testing frontend: $FRONTEND_URL"
          
          # Test main page
          if curl -sf "$FRONTEND_URL" > /dev/null; then
            echo "✅ Frontend main page accessible"
          else
            echo "❌ Frontend main page failed"
            exit 1
          fi
          
          # Test Netlify function
          echo "Testing Netlify chat function..."
          RESPONSE=$(curl -s -X POST "$FRONTEND_URL/.netlify/functions/chat-proxy" \
            -H "Content-Type: application/json" \
            -d '{"messages":[{"role":"user","content":"deployment test"}]}' \
            --max-time 30 || echo "function-timeout")
          
          if echo "$RESPONSE" | grep -q "function-timeout"; then
            echo "⚠️ Netlify function timeout - may need warm-up"
          elif echo "$RESPONSE" | grep -q "error\|Error"; then
            echo "⚠️ Netlify function returned error: $RESPONSE"
          else
            echo "✅ Netlify function responding"
          fi

  # 4. Smoke Tests
  smoke-tests:
    name: Run Smoke Tests
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Chat API
        run: |
          echo "Testing chat endpoint..."
          curl -X POST https://throp-bot-947985992378.us-central1.run.app/api/chat \
            -H "Content-Type: application/json" \
            -d '{"message": "hello"}' \
            --fail-with-body || exit 1
      
      - name: Test X API Integration
        run: |
          echo "Testing X API integration..."
          
          # Test Twitter diagnostics
          DIAG_RESPONSE=$(curl -s https://throp-bot-947985992378.us-central1.run.app/api/twitter/diagnostics --max-time 30)
          
          if echo "$DIAG_RESPONSE" | grep -q "readCapability"; then
            echo "✅ X API diagnostics responding"
            
            # Check if bearer token is working
            if echo "$DIAG_RESPONSE" | grep -q '"readCapability":true'; then
              echo "✅ X API read capability confirmed"
            else
              echo "⚠️ X API read capability may be disabled"
            fi
          else
            echo "❌ X API diagnostics failed"
            echo "Response: $DIAG_RESPONSE"
            exit 1
          fi
      
      - name: Test Hot Takes
        run: |
          echo "Testing hot takes endpoint..."
          curl https://throp-bot-947985992378.us-central1.run.app/api/hot-takes \
            --fail-with-body || exit 1
      
      - name: Test Frontend Proxy
        run: |
          echo "Testing frontend chat proxy..."
          curl -X POST https://throp.ai/.netlify/functions/chat-proxy \
            -H "Content-Type: application/json" \
            -d '{"messages":[{"role":"user","content":"test"}]}' \
            --fail || echo "Chat proxy test completed"
      
      - name: Success Notification
        run: |
          echo "🎉 All deployments successful!"
          echo "Backend: https://throp-bot-947985992378.us-central1.run.app"
          echo "Frontend: https://throp.ai"

  # 5. Rollback notification (manual process)
  notify-on-failure:
    name: Notify on Failure
    needs: [deploy-backend, deploy-frontend, smoke-tests]
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Create Issue on Failure
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Deployment Failed - ${new Date().toISOString()}`,
              body: `The deployment workflow failed. Please check the [workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.
              
              **Manual rollback may be required:**
              - GCP: Use Cloud Console to roll back to previous revision
              - Netlify: Use Netlify dashboard to roll back to previous deploy`,
              labels: ['deployment', 'urgent']
            })
